### ISSUE TITLE
Account creation email opens to a link saying that the token has expired

### ISSUE THREAD

**Issue by Newbytee** [FreeRCT/FreeRCT-website#2]
I tried creating an account on freerct.net, but even if I open the email mere minutes after creating the account, I'm told that the token "already" has expired. This does not seem intentional to me given that the emails say the link is supposed to expire after 7 days.

**Comment by Noordfrees** [comment]
The same bug as last month, with 24.4. plus 7 days equalling the 1.4. instead of the 1.5. …
Please try again to see if c80513fb296bf1e35657fe6375ea5375177cca1b fixed it

**Comment by Newbytee** [comment]
Works now!

**Comment by Newbytee** [comment]
I got this after logging in though:

![image](https://user-images.githubusercontent.com/4428753/164984338-3770c14b-bf27-48f2-bb96-b60c25fd3d9f.png)

:thinking:

**Comment by Noordfrees** [comment]
I get it too…
```gdb
Apr 24 17:38:34 freerct.net bash[1413439]: Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Comparable.compareTo(Object)" because "k1" is null
Apr 24 17:38:34 freerct.net bash[1413439]:         at java.base/java.util.TreeMap.compare(TreeMap.java:1569) ~[na:na]
Apr 24 17:38:34 freerct.net bash[1413439]:         at java.base/java.util.TreeMap.addEntryToEmptyMap(TreeMap.java:776) ~[na:na]
Apr 24 17:38:34 freerct.net bash[1413439]:         at java.base/java.util.TreeMap.put(TreeMap.java:785) ~[na:na]
Apr 24 17:38:34 freerct.net bash[1413439]:         at java.base/java.util.TreeMap.put(TreeMap.java:534) ~[na:na]
Apr 24 17:38:34 freerct.net bash[1413439]:         at java.base/java.util.TreeSet.add(TreeSet.java:255) ~[na:na]
Apr 24 17:38:34 freerct.net bash[1413439]:         at freerct.freerct.FreeRCTApplication.updateAndGetLoggedInUsers(FreeRCTApplication.java:691) ~[classes/:na]
Apr 24 17:38:34 freerct.net bash[1413439]:         at freerct.freerct.FreeRCTApplication.generatePage(FreeRCTApplication.java:876) ~[classes/:na]
Apr 24 17:38:34 freerct.net bash[1413439]:         at freerct.freerct.ErrorHandler.error(ErrorHandler.java:51) ~[classes/:na]
...
```
will investigate

**Comment by Noordfrees** [comment]
I have no idea how this could happen and I couldn't reproduce it locally by registering and activating some accounts. I just restarted the webserver, perhaps it won't happen again…

**Comment by Newbytee** [comment]
Could it be related to that I had two previous failed registration attempts?
